config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "/artwork/:id", to: "main#show", as: "public_artwork"

  resources :artworks do
    member do
      get :preview
    end
    resources :images
  end

  resources :profiles

  scope :admin do
    resources :users
  end

  devise_for :users
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    delete "logout", to: "devise/sessions#destroy"
  end

  post "webhook/chargebee", to: "webhook#chargebee"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  include PgSearch::Model

  validates :title, :medium, :location, :year, presence: true
  validates :units, inclusion: {in: %w[in cm],
                                message: "%{value} is not a valid unit"}

  validate :dimensions

  belongs_to :user
  has_many :images, dependent: :destroy

  pg_search_scope :search, against: [:title, :medium, :description], associated_against: {user: [:first_name, :last_name]}

  scope :is_visible, -> { where("visible = true") }

  scope :with_images, -> {
                        joins(:images).distinct(:artwork_id)
                      }

  MAX_ARTWORK_IMAGES = 3

  def more_images_allowed?
    images.count < MAX_ARTWORK_IMAGES
  end

  private

  def dimensions
    if duration.blank? && (height.blank? || width.blank?)
      errors.add(:either, "Height and Width or Duration is required")
    end
  end

  def artist_name
    user.name
  end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :authenticate_user!
  before_action :confirm_not_curator
  before_action :set_artwork, only: %i[show edit update destroy preview]

  # GET /artworks
  def index
    @artworks = current_user.artworks
  end

  # GET /artworks/1
  def show
  end

  # GET /artworks/1/preview
  def preview
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  def create
    redirect_to artworks_url, notice: "You have uploaded the maximum number of artworks" unless current_user.more_artworks_allowed?

    @artwork = Artwork.new(artwork_params)
    @artwork.user = current_user

    if @artwork.save
      redirect_to @artwork, notice: "Artwork was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /artworks/1
  def update
    if @artwork.update(artwork_params)
      redirect_to @artwork, notice: "Artwork was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /artworks/1
  def destroy
    @artwork.destroy!
    redirect_to artworks_url, notice: "Artwork was successfully destroyed.", status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_artwork
    @artwork = current_user.artworks.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def artwork_params
    params.require(:artwork).permit(:title, :medium, :description, :price, :visible, :duration, :units, :height, :width, :depth, :location, :user_id, :year, :edition)
  end

  def confirm_not_curator
    if current_user.curator?
      redirect_to root_url, notice: "You do not have access to that page"
    end
  end
end

app/views/artworks/_artwork.html.erb
<%= turbo_frame_tag "artwork_#{artwork.id}" do %>
  <div id="<%= dom_id artwork %>">
    <tr>
      <td><%= artwork.id %></td>
      <td><%= link_to artwork.title, artwork %></td>
      <td><%= artwork.medium %></td>
      <td class="hidden sm:table-cell">
        <%= artwork.description %>
      </td>
      <td><% if artwork.visible %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" class="fill-slate-600" viewBox="0 0 16 16">
            <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2z"/>
            <path d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425z"/>
          </svg>
        <% end %>
      </td>
      <td>
        <div class="flex flex-col lg:flex-row gap-1 items-start">
          <% if false && artwork.images.count == 0 %>
            <%= button_to 'Add image', artwork, class: "tw-btn-secondary my-3" %>
          <% end %>
          <% artwork.images.each do |image| %>
            <%= image_tag thumbnail_url(image), class: "min-w-28"  %>
          <% end %>
        </div>
      </td>
      <td>
        <%= button_to( 
          raw('
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
              <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
            </svg>          
          '), 
          artwork, 
          method: :delete, 
          form: { data: { turbo_confirm: 'Are you sure?' } })  %>
      </td>
    </tr>
  </div>
<% end %>

app/views/artworks/_dimensions.html.erb
<div class="text-slate-500">
  <% if @artwork.duration %>
    <%= @artwork.duration %> minutes <br>
  <% end %>
  <% if @artwork.height %>
    <%= @artwork.height %> x <%= @artwork.width %>
    <% if @artwork.depth %>
      x <%= @artwork.depth %>
    <% end %>
    <%= @artwork.units %>
  <% end %>
</div>

app/views/artworks/_form.html.erb
  <%= bootstrap_form_with(model: artwork) do |f| %>
  <%= f.alert_message "Please fix the errors below." %>
  <%= f.text_field :title, help: "required" %>
  <%= f.text_field :medium, help: "required" %>
  <%= f.text_field :edition, help: "if applicable" %>
  <%= f.text_area :description %>
  <%= f.number_field :year, help: "required" %>
  <%= f.number_field :price %>
  <div class="flex flex-col">
    <label>Location:</label>
    <span class="text-sm text-slate-700 my-2">
    Search locations and select from box
    </span>
    <input type="text" value="<%= artwork.location %>" id="location-search"/>
    <%= f.hidden_field :location, id: "location-hidden" %>
    <span class="text-sm text-slate-700 my-2">required</span>
  
    <ul id="suggestion-container" class="my-3 opacity-0 transition-opacity flex flex-col border-1 rounded border-slate-400 gap-2">
      <li class="hidden p-2 cursor-pointer bg-slate-200">test</li>
    </ul>
  </div>
  <%= f.check_box :visible, label: "Visible to curators?" %>
  <fieldset class="border p-2 mb-4">
    <p class="text-secondary">Either duration or heigh and width are required</p>
    <%= f.number_field :duration, label: "Duration (minutes)" %>
    <%= f.select :units, %w[in cm] %>
    <%= f.number_field :height %>
    <%= f.number_field :width %>
    <%= f.number_field :depth %>
  </fieldset>
  <%= f.submit "Save", class: "tw-btn-primary" %>
<% end %>
<%= javascript_include_tag "locationsearch" %>

app/views/artworks/_image.html.erb
<div class="h-full flex flex-col justify-between">
  <%= image_tag large_url(i), alt: i.caption, class: "rounded lg:w-full" %>
  <div class="flex justify-between mt-2">
    <i><%= i.caption %></i>
    <%= button_to( 
      raw('
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
          <title>Delete image</title>
          <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5M11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47M8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5"/>
        </svg>          
      '), 
      [@artwork, i], 
      method: :delete,
      class: "inline-block",
      form: { data: { turbo_confirm: 'Are you sure you want to delete the image?' } })  %> 
    </div>         
</div>

app/views/artworks/_info.html.erb
<div class="">
      <h1 class="text-2xl mb-0 font-normal">
        <%= @artwork.user.name %>
      </h1>
      <h2 class="text-2xl font-normal italic text-black mb-3">
        <%= @artwork.title %>, (<%= @artwork.year %>)
      </h2>
      <div class="text-slate-500">
        <%= @artwork.medium %>
      </div>
      <% if @artwork.edition.present? %>
        <div class="text-slate-500">
          ed: <%= @artwork.edition %>
        </div>
      <% end %>
      <%= render "artworks/dimensions" %>
      <div class="text-slate-500">
        Location: <%= @artwork.location %>
      </div>
      <% if @artwork.price.present? %>
      <div class="text-xl py-2">
        Price: <%= @artwork.price %>
      </div>
      <% end %>
      <% if @artwork.description.present? %>
        <div class="mt-2 text-slate-500">
          <%= @artwork.description %>
        </div>
      <% end%>
      <div class=" text-slate-700 flex gap-4 mt-4">
        <svg width="20" height="20" class="<%= @artwork.visible ? "fill-slate-800" : "fill-slate-300" %>" viewBox="0 0 16 16">
          <title class="w-full h-full"><%= @artwork.visible ? "" : "Not " %> visible to curators</title>
          <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
          <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
        </svg>
        <span class="text-md"><%= !@artwork.visible ? "Not" : "" %> Visible to curators</span>
      </div>

    </div>

app/views/artworks/edit.html.erb
<div class="w-full max-w-xl">
  <%= render "form", artwork: @artwork %>
  <br>
  <div>
    <%= link_to "Show this artwork", @artwork %> |
    <%= link_to "Back to artworks", artworks_path %>
  </div>
</div>

app/views/artworks/index.html.erb
  
<h4>Add up to 10 Artworks</h4>
<% if current_user.more_artworks_allowed? %>
  <%= link_to "Add new artwork", new_artwork_path, class: "tw-btn-secondary inline-block my-3" %>
<% end %>
<table class="table">
  <thead  class="text-sm">
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Medium</th>
      <th class="hidden sm:table-cell">Description</th>
      <th>Visible to curators?</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody id="artworks">
    <% @artworks.each do |artwork| %>
      <%= render artwork %>
    <% end %>
  </table>
</div>

app/views/artworks/new.html.erb
<div class="container col-md-5">
  <h4>New artwork</h4>
  <%= render "form", artwork: @artwork %>
</div>

app/views/artworks/preview.html.erb
<div class="container">
  <%= link_to "exit preview", @artwork %>
  <section class="image-grid mt-2">
    <div class="row gy-4">
      <% @artwork.images.each do |i| %>
        <div class="col-4">
          <a data-fslightbox href="<%= i.file.url %>">
            <%= image_tag large_url(i), alt: i.caption %>
          </a>
          <br>
          <i><%= i.caption %></i>
        </div>
      <% end %>
    </div>
  </section>
  <div class="row mt-2">
    <div class="col-4">
      <div><strong><%= @artwork.title %></strong> (<%= @artwork.year %>)<br>
        <%= @artwork.medium %>
      </div>
      <% if @artwork.edition.present? %>
        <div>
          ed: <%= @artwork.edition %>
        </div>
      <% end %>
      <%= render "dimensions" %>
      <div>
        Location: <%= @artwork.location %>
      </div>
      <div>
        Price: <%= @artwork.price.present? ? number_to_currency(@artwork.price, unit: "", precision: 0) : "none" %>
      </div>
      <div class="pink">
        <%= @artwork.visible ? "Not " : "" %> Visible to Curators
      </div>
      <% if @artwork.description.present? %>
        <div class="mt-2">
          <div class="fw-bold">Description</div>
          <%= @artwork.description %>
        </div>
      <% end%>
    </div>
  </div>
</div>
<%= javascript_include_tag "lightbox-refresh" %>

app/views/artworks/show.html.erb
<div class="flex flex-col max-w-5xl mx-auto  gap-6 h-auto">
  <!-- info -->
  <div class="">
    <% artwork = @artwork %>
    <%= render "info" %>
  </div>
  <!-- images -->
  <h3 class="mt-4 text-xl">Images</h3>
  <div class="border-slate-300 border-1 p-4 flex gap-4 lg:gap-6 flex-col sm:flex-row sm:flex-wrap">
    
      <% @artwork.images.each do | image |  %>
      <div class="sm:w-[calc(50%-15px)] lg:w-[calc(33%-15px)]">
        <%= render "image", i: image %>
      </div>
      <% end %>
      <% if @artwork.more_images_allowed? %>
      <div class="bg-slate-100 sm:w-[calc(50%-15px)] lg:w-[calc(33%-15px)]">
          <label class="z-10 relative flex justify-center  items-center cursor-pointer px-2 py-6" for="addimage">
            <!-- filter hidden input. works for keeping the state -->
            <input class="peer/addimage hidden" type="checkbox" id="addimage" />   
            <a alt="add image" class="absolute block z-20 opacity-100 hover:no-underline transition-opacity peer-checked/addimage:opacity-0">
              <div class="flex flex-col items-center">
                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="w-8 h-8" viewBox="0 0 16 16">
                  <path d="M8 6.5a.5.5 0 0 1 .5.5v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7a.5.5 0 0 1 .5-.5"/>
                  <path d="M14 4.5V14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h5.5zm-3 0A1.5 1.5 0 0 1 9.5 3V1H4a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1V4.5z"/>
                </svg>
                <div class="mt-4 text-sm">Add artwork image (Up to <%= Artwork::MAX_ARTWORK_IMAGES %>)</div>
              </div>
            </a>            
            <div class="opacity-0 peer-checked/addimage:opacity-100 transition-opacity">       
              <h5>Upload artwork image:</h5>
              <%= render "images/form", artwork: @artwork, image: @artwork.images.new %>
            </div>
          </label>
      </div> 
      <% end %>
    </div> 
    <!-- actions -->
    <div class="mt-4 flex content-center gap-3">
      
      <%= link_to "Edit this artwork", edit_artwork_path(@artwork), class: "tw-btn-secondary" %>
      <%= button_to "Delete this artwork", @artwork, method: :delete, class: "tw-btn-danger", form: { data: { turbo_confirm: 'Are you sure?' } } %>

    </div>
  </div>


</div>