config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "/artwork/:id", to: "main#show", as: "public_artwork"

  resources :artworks do
    member do
      get :preview
    end
    resources :images
  end

  resources :profiles

  scope :admin do
    resources :users
  end

  devise_for :users
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    delete "logout", to: "devise/sessions#destroy"
  end

  post "webhook/chargebee", to: "webhook#chargebee"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :artwork
  has_one_attached :file

  validates :file, presence: true
  validate :valid_image

  before_destroy :purge_file

  def is_video?
    file&.blob&.content_type&.include?("video")
  end

  private

  def valid_image
    return unless file.attached?
    unless file.blob.byte_size <= 10.megabyte
      errors.add(:file, "is too large")
    end

    unless /^image|video/.match?(file.content_type)
      errors.add(:file, "must be a JPEG, PNG, or Video")
    end
  end

  def purge_file
    file.purge
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_artwork
  before_action :set_image, only: %i[show edit update destroy]

  # GET /images
  def index
    @images = @artwork.images
  end

  # GET /images/1
  def show
  end

  # GET /images/new
  def new
    @image = @artwork.images.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  def create
    @image = @artwork.images.new(image_params)

    if @image.save
      redirect_to @artwork
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /images/1
  def update
    if @image.update(image_params)
      redirect_to artwork_images_url(@artwork), notice: "Image was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /images/1
  def destroy
    @image.destroy!
    redirect_to @artwork, status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = @artwork.images.find(params[:id])
  end

  def set_artwork
    @artwork = current_user.artworks.find(params[:artwork_id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image).permit(:caption, :file)
  end
end

app/views/images/_form.html.erb
<%= form_with(model: [artwork, image]) do |f| %>
  <div class="flex mt-3 flex-col gap-3">
    <div class="col-span-full">
      <%= f.label :caption, 'Caption',  class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.text_field :caption, class: "block w-full max-w-48 rounded-md border-0 py-1.5 text-gray-900
                                        ring-1 ring-inset ring-gray-400 placeholder:text-gray-400 focus:ring-2 
                                        focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" %>
    </div>
    <div>
      <%= f.label :file, 'File',  class: "block text-sm font-medium leading-6 text-gray-900" %>
      <%= f.file_field :file, class: "block w-full p-2 max-w-64 rounded-md border-0 py-1.5 text-gray-900 ring-1 ring-inset ring-gray-400 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-500 sm:text-sm sm:leading-6" %>
    </div>

    <%= f.submit "Add", class: "tw-btn-primary" %>
  </div>

<% end %>

app/views/images/_image.html.erb
<div id="<%= dom_id image %>">
  <div>
    <%= image_tag image.file.url(transformation: [{width: 300}]) %>
  </div>
  <p>
    <i><%= image.caption %></i>
  </p>
</div>

app/views/images/edit.html.erb
<div class="container col-md-5">
  <h4>Editing image for "<%= @artwork.title %>"</h4>
  <%= render "form", image: @image %>
  <br>
  <div>
    <%= link_to "Back to images", artwork_images_path(@artwork) %>
  </div>

app/views/images/index.html.erb
<h4>Images</h4>
<div id="images">
  <% @images.each do |image| %>
    <%= render image %>
  <% end %>
</div>
<%= link_to "New image", new_artwork_image_path %>

app/views/images/new.html.erb
<div class="container col-md-5">
  <h4>New image for "<%= @artwork.title %>"</h4>
  <%= render "form", artwork: @artwork, image: @image %>
  <br>
  <div>
    <%= link_to "Back to images", artwork_images_path(@artwork) %>
  </div>
</div>

app/views/images/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @image %>

<div>
  <%= link_to "Edit this image", edit_image_path(@image) %> |
  <%= link_to "Back to images", images_path %>

  <%= button_to "Destroy this image", @image, method: :delete %>
</div>