config/routes.rb
Rails.application.routes.draw do
  root "main#index"
  get "/artwork/:id", to: "main#show", as: "public_artwork"

  resources :artworks do
    member do
      get :preview
    end
    resources :images
  end

  resources :profiles

  scope :admin do
    resources :users
  end

  devise_for :users
  devise_scope :user do
    get "login", to: "devise/sessions#new"
    delete "logout", to: "devise/sessions#destroy"
  end

  post "webhook/chargebee", to: "webhook#chargebee"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check
end

app/views/layouts/_navbar.html.erb
<nav class="bg-white shadow-md shadow-slate-200 border-b-slate-200 border-1">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex flex-1 items-center justify-between sm:items-stretch ">
        <div class="flex flex-shrink-0 items-center">
          <a class="flex items-center hover:no-underline" href="/">
            <img class="h-8 w-auto" src="/logo.png" alt="Netvvrk Members Database" >
            <span class="px-2 text-black">Netvvrk Members Database</span>
          </a>
        </div>
        <!-- new button -->
        <label class="lg:relative lg:flex lg:flex-1 z-40 cursor-pointer px-2 py-6 grow-1" for="mobile-menu">
          <!-- mobile menu hidden input. works for keeping the state -->
          <input class="peer hidden" type="checkbox" id="mobile-menu" />
          <!-- mobile menu icon. -->
          <div class="lg:hidden relative z-50 block h-[1px] w-7 bg-black bg-transparent content-[''] before:absolute before:top-[-0.35rem] before:z-50 before:block before:h-full before:w-full before:bg-black before:transition-all before:duration-200 before:ease-out before:content-[''] after:absolute after:right-0 after:bottom-[-0.35rem] after:block after:h-full after:w-full after:bg-black after:transition-all after:duration-200 after:ease-out after:content-[''] peer-checked:bg-transparent before:peer-checked:top-0 before:peer-checked:w-full before:peer-checked:rotate-45 before:peer-checked:transform after:peer-checked:bottom-0 after:peer-checked:w-full after:peer-checked:-rotate-45 after:peer-checked:transform"></div>
          <div class="lg:flex lg:flex-1 bg-white border-l-slate-200 border-1 lg:border-white lg:ml-6  lg:static lg:top-auto lg:translate-x-0 fixed top-0 right-0 z-40 h-full w-full translate-x-full overflow-y-auto overscroll-y-none transition duration-500 peer-checked:translate-x-1 peer-checked:sm:translate-x-1/3 peer-checked:md:translate-x-1/2">
            <div class="flex lg:flex-1 flex-col pt-12 lg:pt-0 lg:flex-row">
              <% if user_signed_in? %>
                <% if current_user.show_artworks? %>
                  <%= link_to "Manage Artworks", artworks_url, class: "text-black hover:no-underline hover:text-slate-600 hover:text-black rounded-md px-3 py-2 text-base font-medium" %>
                <% end %>
                <% if current_user.show_users? %>
                  <%= link_to "Users", users_url, class: "text-black hover:no-underline hover:text-slate-600 hover:text-black rounded-md px-3 py-2 text-base font-medium" %>
                <% end %>
              <% end %>
            </div>
            <div class="inset-y-0 right-0 flex items-start gap-y-2 lg:gap-y-0 lg:items-center flex-col lg:flex-row  static inset-auto pr-0 ml-2 xmt-4 lg:mt-0">
              <% if user_signed_in? %>
                <% if current_user.artist? %>
                  <%= link_to(
                    "edit profile",
                    edit_profile_path(Profile.find_or_create_by(user_id: current_user.id)),
                    class: "tw-btn-secondary lg:mr-2"
                  ) %>
                <% end %>
                <%= button_to(
                  "Log Out",
                  logout_path,
                  method: :delete,
                  class: "tw-btn-secondary"
                ) %>
              <% else %>
                <%= button_to(
                "Log In",
                login_path,
                method: :get,
                class: "tw-btn-secondary"
              ) %>
              <% end %>
            </div>
          </div>
        </label>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netvvrk Members Database</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="mx-auto max-w-7xl p-4  sm:px-6 lg:p-8">
      <% flash.each do |key, value| %>
        <div class="py-2 mb-4 text-md border-b w-fit <%= key == "notice" ? "border-slate-200 text-slate-600" : "text-red-500 border-red-200" %>">
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <% if is_production? %>
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-CD1ZMCYVTF"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-CD1ZMCYVTF');
      </script>
    <% end %>
  </body>
</html>